# Generated by Django 6.0.5 on 2026-05-09 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název týmu musí být vyplněn'}, help_text='Zadejte název týmu', max_length=100, verbose_name='Název týmu')),
                ('mesto', models.CharField(error_messages={'blank': 'Město musí být vyplněno'}, help_text='Zadejte město týmu', max_length=100, verbose_name='Město')),
                ('zalozen', models.IntegerField(help_text='Zadejte rok založení (1800 - 2100)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok založení')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno hráče musí být vyplněno'}, help_text='Zadejte jméno hráče', max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení hráče musí být vyplněno'}, help_text='Zadejte příjmení hráče', max_length=50, verbose_name='Příjmení')),
                ('datum_narozeni', models.DateField(help_text='Zadejte datum narození', verbose_name='Datum narození')),
                ('narodnost', models.CharField(error_messages={'blank': 'Národnost musí být vyplněna'}, help_text='Zadejte národnost hráče', max_length=50, verbose_name='Národnost')),
                ('pozice', models.CharField(choices=[('brankár', 'Brankář'), ('obránce', 'Obránce'), ('záložník', 'Záložník'), ('útočník', 'Útočník')], help_text='Vyberte pozici hráče', max_length=20, verbose_name='Pozice')),
                ('cislo_dresu', models.PositiveIntegerField(help_text='Zadejte číslo dresu (1 - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu')),
                ('preferovana_noha', models.CharField(choices=[('pravá', 'Pravá'), ('levá', 'Levá'), ('obě', 'Obě')], default='pravá', max_length=10, verbose_name='Preferovaná noha')),
                ('datum_pristupu', models.DateField(blank=True, null=True, verbose_name='Datum přístupu do týmu')),
                ('tym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hraci', to='seznamHracu.tym', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(help_text='Zadejte datum zápasu', verbose_name='Datum zápasu')),
                ('goly_domaci', models.PositiveIntegerField(default=0, verbose_name='Góly domácích')),
                ('goly_hoste', models.PositiveIntegerField(default=0, verbose_name='Góly hostů')),
                ('domaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci_zapasy', to='seznamHracu.tym', verbose_name='Domácí tým')),
                ('hoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostujici_zapasy', to='seznamHracu.tym', verbose_name='Hostující tým')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='StatistikaHrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goly', models.PositiveIntegerField(default=0, verbose_name='Góly')),
                ('asistence', models.PositiveIntegerField(default=0, verbose_name='Asistence')),
                ('minuty', models.PositiveIntegerField(default=0, help_text='Zadejte počet odehraných minut (0 - 120)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Odehrané minuty')),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiky', to='seznamHracu.hrac', verbose_name='Hráč')),
                ('zapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiky', to='seznamHracu.zapas', verbose_name='Zápas')),
            ],
            options={
                'verbose_name': 'Statistika hráče',
                'verbose_name_plural': 'Statistiky hráčů',
                'unique_together': {('hrac', 'zapas')},
            },
        ),
    ]
